audit_header: false
title: FYKES Leadership Training
description: Tiffany Fykes, a top Real Estate Agent in Nashville, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Tiffany Fykes
  title:
  license_number:
  about_markdown: |
    Ranking in the top 1% of all real estate agents across the country, having built a million dollar business in less than 4 years, and having more than 8 years of experience under her belt, Tiffany Fykes has developed a vast knowledge of the ever-changing business of real estate.

    The founder and CEO of FYKES Realty Group, Tiffany’s goal is to share what she knows with others. Her influence spans to reach many individuals across the country as she has taught all the way from Seattle to Baltimore to Atlanta and on the stages of Family Reunion. Her teachings are geared towards growth through professional development courses and Wealthy Agent Mindset (WAM), which is Tiffany’s recurring speaking engagement that teaches agents how to build wealth. She also fosters and encourages a deep value and love of balancing personal lives in a professional world through creating experiences.
  market: Nashville
  brand: The FYKES Realty Group
  brokerage: Keller Williams
  address: 4811 Trousdale Dr. Suite-D, Nashville, TN 37220
  phone: 615-427-8436
  phone_type:
  phone2:
  phone2_type:
  email: tiffany@fykgroup.com
  url: https://www.FykesRealtyGroup.com

lender:
  show_section: true
  header_text: Senior Buyer's Agent
  headshot_path: /img/lender-headshot.jpg
  # logo_path: /img/logo.png
  logo_path_2:
  name: John Griffin
  # brand: Lender Co.
  # phone: 555-555-5555
  # email: bill@murray.com
  # url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/FykesRealtyGroup/
  linkedin_url: https://www.linkedin.com/company/fyk-realty-group/
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/fykesrealty
  instagram_url: https://www.instagram.com/fykesrealtynashville/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#d31145'
  theme_color: '#a7a9ac'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
